config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "todos", to: "todos#index"
  # post "todos", to: "todos#create"
  # get "todos/:id", to: "todos#show"

  # root :to => "/"
  get "/" => "home#index"
  resources :todos
  post "users/login", to: "users#login"
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true

  belongs_to :user

  def to_pleasant_string
    is_completed = completed ? "[X]" : "[ ]"
    "#{id}. #{due_date.to_s(:long)} #{todo_text} #{is_completed}"
  end

  def due_today?
    due_date == Date.today
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.overdue
    where("due_date < ?", Date.today)
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.completed
    where(completed: true)
  end

  def self.not_completed
    where(completed: false)
  end

  def self.show_list
    puts "My Todo-list\n\n"

    puts "Overdue\n"
    puts overdue.map { |todo| todo.to_displayable_string }
    puts "\n\n"

    puts "Due Today\n"
    puts due_today.map { |todo| todo.to_displayable_string }
    puts "\n\n"

    puts "Due Later\n"
    puts due_later.map { |todo| todo.to_displayable_string }
    puts "\n\n"
  end

  def self.add_task(todo_object)
    text = todo_object[:todo_text]
    days = todo_object[:due_in_days]
    Todo.create!(todo_text: text, due_date: Date.today + days, completed: false)
  end

  def self.mark_as_complete(todo_id)
    todo = Todo.find_by("id = ?", todo_id)
    todo[:completed] = true
    todo.save
    todo
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
  has_many :todos

  def to_pleasant_string
    "#{id}. #{name.to_s} #{email} #{password}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    @current_user_id = session[:current_user_id]
    if @current_user_id
      @current_user = User.find(@current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index" #, locals: { user_name: current_user.first_name }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid. Please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def index
    render plain: User.order("id").map { |user| user.to_pleasant_string }
  end

  def show
    id = params[:id]
    user = User.find(id)
    render plain: user.to_pleasant_string
  end

  def create
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end

  def login
    email = params[:email]
    password = params[:password]
    user = User.find_by(email: email, password: password)
    render plain: user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">Welcome to the Todo homepage</h1>

<h3 class="Home-authenticate">
  If you are a new user, then <%= link_to :"Sign up here!", new_user_path %>
</h3>

<h3 class="Home-authenticate">
  If you are a existing user, then <%= link_to :"Sign in here!", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Todo Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"><%= section_title %></p>
    <p class="TodoSectionTitle-remainingCount">
      <%= todos.completed.count %> / <%= todos.count %>
    </p>
  </div>
  <ul>
    <% todos.all.each do |todo| %>
        <li class="TodoItem">
          <label class="TodoItem-container">
            <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
              <%= check_box_tag("completed", todo.completed ? 0 : 1, todo.completed, class: "TodoItem-checkbox", :onclick => "this.form.submit()") %>
            <% end %>
            <p class='<%= todo.completed ? "TodoItem-text TodoItem-completed" : "TodoItem-text" %>'>
              <%= todo.todo_text %>
            </p>
            <% if show_due_date %>
              <p class="TodoItem-remainingDate"> <%= todo.due_date.to_s(:short) %> </p>
            <% end %>
            <a class="TodoItem-delete" href="javascript:void(0)">
              <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
                <%= image_submit_tag("delete.png") %>
              <% end %>
            </a>
          </label>
        </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">

  <article>
    <h1 class="TodoPage-title">My To-do List</h1>

    <%= form_with(url: "/todos/", method: "post", class: "AddTodo") do %>
      <%= text_field_tag("todo_text", nil, placeholder: "What's next?", class: "AddTodo-text") %>
      <%= date_field_tag("due_date", nil, class: "AddTodo-date") %>
      <%= submit_tag("Add", class: "AddTodo-button") %>
    <% end %>

    <%= render partial: "todo-section", locals: {
                 section_title: "Overdue",
                 todos: @todos.overdue.not_completed,
                 show_due_date: true,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Today",
                 todos: @todos.due_today,
                 show_due_date: false,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Later",
                 todos: @todos.due_later,
                 show_due_date: true,
               } %>

  </article>
</main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user!</p>

<section class="UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class="form-section">
      <p class="FormInput-label">First Name: </p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="form-section">
      <p class="FormInput-label">Last Name: </p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="form-section">
      <p class="FormInput-label">Email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="form-section">
      <p class="FormInput-label">Password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="form-section">
      <%= form.submit "Sign-up", class: "Form-submit" %>
    </div>
  <% end %>
</section>